#-------------------------------------------------------------------------
# TITLE: 
#    pkgIndex.tcl
#
# PROJECT:
#    tcl-quill: Quill Project Automation System for Tcl/Tk
#
# DESCRIPTION:
#    tcl-quill quillinfo(n): pkgIndex file
#
#    Generated by Quill
#-------------------------------------------------------------------------

package ifneeded quillinfo 1.0 [list source [file join $dir pkgModules.tcl]]
