#-------------------------------------------------------------------------
# TITLE: 
#    quillinfo.tcl
#
# PROJECT:
#    tcl-quill: Quill Project Build System for Tcl/Tk
#
# DESCRIPTION:
#    Project Metadata
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Exported Commands

namespace eval ::quillinfo {
    variable meta
    array set meta {apps quill description {Quill Project Build System for Tcl/Tk} homepage http://github.com/wduquette/tcl-quill version 0.1a0 url http://my.home.page project tcl-quill}

    namespace export \
        project      \
        description  \
        version      \
        homepage

    namespace ensemble create
}

#-------------------------------------------------------------------------
# Commands

# project
#
# Returns the project name.

proc ::quillinfo::project {} {
    variable meta
    return $meta(project)
}

# description 
#
# Returns the project's description.

proc ::quillinfo::description {} {
    variable meta
    return $meta(description)
}

# version 
#
# Returns the project version number.

proc ::quillinfo::version {} {
    variable meta
    return $meta(version)
}

# homepage 
#
# Returns the project home page URL.

proc ::quillinfo::homepage {} {
    variable meta
    return $meta(homepage)
}