#-------------------------------------------------------------------------
# TITLE: 
#    quillinfo.tcl
#
# PROJECT:
#    tcl-quill: Quill Project Automation System for Tcl/Tk
#
# DESCRIPTION:
#    Project Metadata
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Exported Commands

namespace eval ::quillinfo {
    variable meta
    array set meta {version-zipfile::encode 0.3 gui-quill 0 url http://my.home.page description {Quill Project Automation System for Tcl/Tk} provides quill homepage http://github.com/wduquette/tcl-quill requires {Tcl snit textutil::expander zipfile::encode} exetype-quill exe version-textutil::expander 1.3.1 version-snit 2.3 local-Tcl 0 distpat-install-%platform {
    %apps
    %libs
    docs/*.html
    docs/*/*.html
    docs/*.md
    LICENSE
    README.md
} apps quill local-zipfile::encode 0 local-textutil::expander 0 local-snit 0 version 0.4.1 version-Tcl 8.6 project tcl-quill dists install-%platform}

    namespace export \
        project      \
        description  \
        version      \
        homepage     \
        isgui

    namespace ensemble create
}

#-------------------------------------------------------------------------
# Commands

# project
#
# Returns the project name.

proc ::quillinfo::project {} {
    variable meta
    return $meta(project)
}

# description 
#
# Returns the project's description.

proc ::quillinfo::description {} {
    variable meta
    return $meta(description)
}

# version 
#
# Returns the project version number.

proc ::quillinfo::version {} {
    variable meta
    return $meta(version)
}

# homepage 
#
# Returns the project home page URL.

proc ::quillinfo::homepage {} {
    variable meta
    return $meta(homepage)
}

# isgui app
#
# app   - An app name for this project.
#
# Returns true if the app is a GUI and false otherwise.

proc ::quillinfo::isgui {app} {
    variable meta

    if {[info exists meta(gui-$app)]} {
        return $meta(gui-$app)
    } else {
        return 0
    }
}
