#-------------------------------------------------------------------------
# TITLE: 
#    element_package.tcl
#
# AUTHOR:
#    Will Duquette
# 
# PROJECT:
#    Quill: Project build system for Tcl/TK
#
# DESCRIPTION:
#    Project Element: package skeleton
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# package Templates

::quillapp::element public package {project package} 2 2 \
     ::quillapp::packageElement

# package project package
#
# project - The project name
# package - The package name
# 
# Saves the package element tree.

proc ::quillapp::packageElement {project package} {
    gentree \
        lib/$package/pkgIndex.tcl   [pkgIndex $project $package]    \
        lib/$package/pkgModules.tcl [pkgModules $project $package]  \
        lib/$package/$package.tcl   [pkgFile $project $package]
}

# pkgIndex project package
#
# pkgIndex.tcl file for the $package(n) package.

maptemplate ::quillapp::pkgIndex {project package} {
    #-------------------------------------------------------------------------
    # TITLE: 
    #    pkgIndex.tcl
    #
    # PROJECT:
    #    %project: Your Description
    #
    # DESCRIPTION:
    #    %package(n): pkgIndex file
    #
    #    Generated by Quill
    #
    #-------------------------------------------------------------------------

    # -quill-begin-ifneeded DO NOT EDIT BY HAND
    package ifneeded %package 0.0a0 [list source [file join $dir pkgModules.tcl]]
    # -quill-end-ifneeded
}

# pkgModules project package
#
# pkgModules.tcl file for the package(n) package.

maptemplate ::quillapp::pkgModules {project package} {
    #-------------------------------------------------------------------------
    # TITLE: 
    #    pkgModules.tcl
    #
    # PROJECT:
    #    %project: Your Package Description
    #
    # DESCRIPTION:
    #    package(n): Package Loader
    #
    #    Generated by Quill
    #
    #-----------------------------------------------------------------------

    # -quill-begin-provide DO NOT EDIT BY HAND
    package provide %package 0.0a0
    # -quill-end-provide

    #-----------------------------------------------------------------------
    # Get the library directory

    namespace eval ::%package:: {
        variable library [file dirname [info script]]
    }

    source [file join $::%package::library %package.tcl]
}

# pkgFile project package
#
# $package.tcl file for the $package(n) package.

maptemplate ::quillapp::pkgFile {project package} {
    #-------------------------------------------------------------------------
    # TITLE: 
    #    %package.tcl
    #
    # PROJECT:
    #    %project: Your Package Description
    #
    # DESCRIPTION:
    #    %package(n): Implementation File
    #
    #-------------------------------------------------------------------------

    #-------------------------------------------------------------------------
    # Exported Commands

    namespace eval ::%package {
        namespace export \\
            hello
    }

    #-------------------------------------------------------------------------
    # Commands

    # hello
    #
    # Dummy procedure

    proc ::%package::hello {} {
        puts "Hello, world!"
    }
}
